<b>Privacy</b><br><br>
<b>Introduction</b>
<br><br>The Risk Management Office (RMO) team welcomes you to this platform, which allows us to process your data more efficiently, and make it available to all registered user again, provided that you agree. We are responsible for all German Governmental Develop Organization (GGDO) as well as Non Governmental Organizations (NGO). All their staff including all employed consultants have to be registered and they are the all portal users (approximately 1000-1500 people). Inside the portal there are different user groups. The project management team includes the project manager and their deputies who are responsible for you and your colleagues. The project management team includes normally three people. Ask your project manager for the actual count. The RMO administration is not the entire RMO. The group of the RMO administration includes at least one representative of each RMO as well as of each GGDO of each region. That means that this user group counts at least 20 people up to 50 people.
Although the services offered by the platform are somewhat restricted at present, they are currently being developed further.<br>
We use your data for the following main purposes:
<ul>
<li>We have to know that you are employed by an included organization. Therefore we are responsible for your security.</li>
<li>We provide you with security related information via SMS and email.</li>
<li>We support the main office in some administrative processes. Therefore you will get some additional information.</li></ul>
If you are non national employee then we are transmitting weekly the following data to the German embassy: first name, family name, job title, organization, call sign, email, mobiles and nationality. Your job title and your call sign will be transmitted due to make the communication easier for the embassy. In emergency cases the embassy will use our VHF frequencies as well. To address the team leader or you the embassy need these information.
<br><br><b>Invitation</b><br>
During the invitation process, your family name, your given name, your email address, job title, nationality, project, call sign suffix, date of invitation and organisation were saved. You can change your given name, family name and email at any stage. We need these data, in order to address you correctly. We use your email address to send you information electronically. In order to prevent misuse, you cannot change your job title, nationality, project, call sign suffix and organisation. Your RMO administration team can change all of these data, as can the project management team (the only thing the latter cannot change is the project). We use the organisation, the project and the job title in order to automatically assign you to corresponding information distribution lists. We also use the job title to decide whether you will be assigned access to the system. We use the nationality to arrange for your evacuation. The call sign suffix is used to have a uniform call sign for you countrywide. We use the date of invitation to track if you finish your registration within one week. If you didn't finish the registration after one week you will get an reminder email every day. 
<br><br><b>Profile data</b><br>
Once you have registered fully, we save your title, place, date of end of contract/departure from Afghanistan, date of birth, three mobile phone numbers, whether you have agreed to this declaration, and your agreement to an entry for you in the phone book. We need your location for the regional distribution list and for evacuation, if necessary. We use the date of departure/end of contract to establish how long we are responsible for you and for how long we are allowed to send you information. The mobile phone numbers allow us to contact you, and send you information by text message. We only use the first two numbers (and not the satellite phone number) for text messages. If you are not a member of support staff, only the title, date of birth, alternative mobile phone number and satellite phone number are optional. Data must be entered in all other fields. If you are a driver or security guard, an email address entry is also optional. If you are another employee working as support staff, the mobile phone number is also optional. We also save when you last changed your profile, so that we can, if necessary, remind you every 90 days that you must update your data. The system also contains an active field that allows deactivation ahead of schedule.
<br><br><b>Additional data</b><br>
Once you have registered successfully and saved your profile data, you are obliged to enter travels within and outside of the country. The reason for your travel is irrelevant. For your travels, we save the place, start date and end date. We use this information to evacuate you from the correct location in case of emergency, and to temporarily provide you with any other regional information required. You can also nominate contact persons. In case of emergency, we pass on this information to the necessary authority. Serious illness/injury, kidnapping or death constitute an emergency. We save the family name, given name and telephone number of your possible contact persons.
<br><br><b>Deletion</b><br>
Your data (including the contact persons and travels) are automatically deleted 180 days after your last deactivation.
<br><br><b>Access to your data</b><br>
If you agree with this declaration:
<ul>
<li>you allow us to process and save your data as outlined above,</li>
<li>all members of the RMO administration team (not the entire RMO) have read access to your data,</li>
<li>all RMO administrators and your project management will have write access to your nationality, job title, organization, active field and project. (The project management team can change all of this data except for the project),</li>
<li>all portal users have read access to your project, organization, family name, given name, job title, email and telephone numbers if you do not change the visibility rights,</li>
<li>the RMO will send you information by email and text message,</li>
<li>If you are an international colleague the following data will be transmitted to the German embassy: your name, your first name, your office location, your project, your job title, your organization, your entered email address, all your entered mobiles and your country of nationality,</li>
<li>If your are a national colleague the following data will be transmitted to the medical service provider:your name, your first name, your location and your project,</li>
<li>If you are a team leader (you have the system role project manager or project representative) your contact data (first and family name, your mobile numbers and your email address) will be transmitted to the medical service provider.</li>
</ul>
If you do not agree with these provisions, the RMO is informed, and we are not able to provide you any security related information. In addition we are not able to include you in our attendance sheet what means that you are not part of our HRE (Hibernate/Relocation/Evacuation) plans.<br>
Please refer to the internal policy of your organization for the detailed consequences. Maybe your contract will terminate.
<br><br><b>Cancellation of this agreement</b><br>
Please contact your team leader if you want to cancel this agreement.<br><br><br><br><br><br><br><br>